# Generated by Django 5.1.6 on 2025-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregister',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
