# Generated by Django 5.1.6 on 2025-04-24 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companyregister_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 12 digits.', regex='^\\d{10,12}$')])),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
