# Generated by Django 5.1.6 on 2025-04-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_companyregister_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(blank=True, max_length=300, null=True)),
                ('job_type', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('CGPA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('LPA', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('required_skill', models.CharField(blank=True, max_length=5000, null=True)),
                ('qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='No description provided', null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('register_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.companyregister')),
            ],
        ),
    ]
